apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: default
type: Opaque
data:
  POSTGRES_DB: bXlkYXRhYmFzZQ==
  POSTGRES_USER: bXl1c2Vy
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==